apiVersion: v1
kind: Namespace
metadata:
  name: custom
---
apiVersion: v1
kind: Service
metadata:
  name: custom-service
  namespace: custom
  labels:
    app: custom-website
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: 'http-port'
  type: NodePort
  selector:
    app: custom-website
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: custom-ingress
  # Assumes a global static ip with the same name exists.
  # You can acquire a static IP by running
  # gcloud compute addresses create test-ip --global
  annotations:
    kubernetes.io/ingress.global-static-ip-name: custom-ip
  labels:
    app: custom-website
  namespace: custom
spec:
  backend:
    serviceName: custom-service
    servicePort: 8080
  rules:
    - host: custom.com
      http:
        paths:
        - path: /
          backend:
            serviceName: custom-service
            servicePort: 8080
  tls:
  - hosts:
    - custom.com
    secretName: custom-tls
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
    name: custom-tls
    namespace: custom
spec:
    secretName: custom-tls
    issuerRef:
        name: letsencrypt-prod
        kind: ClusterIssuer
    commonName: custom.com
    dnsNames:
    - custom.com
    acme:
        config:
        - http01:
              ingress: custom-ingress
          domains:
          - custom.com
