stages:
- build
- test
- release

variables:
    # When using dind service we need to instruct docker, to talk with the
    # daemon started inside of the service. The daemon is available with
    # a network connection instead of the default /var/run/docker.sock socket.
    #
    # The 'docker' hostname is the alias of the service container as described at
    # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
    #
    # Note that if you're using Kubernetes executor, the variable should be set to
    # tcp://localhost:2375 because of how Kubernetes executor connects services
    # to the job container
    DOCKER_HOST: tcp://docker:2375/
    # When using dind, it's wise to use the overlayfs driver for
    # improved performance.
    DOCKER_DRIVER: overlay2

services:
- docker:dind

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
#  - echo "$DOCKER_AUTH_CONFIG" >> "$HOME/.docker/config.json"

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches
    - src/kubernetes

build:
  image: gradle:jdk10
  stage: build
  script:
    - ./gradlew --no-daemon build
  artifacts:
    paths:
      - project_website/build/libs/*.war
    expire_in: 1 week

test:
  image: gradle:jdk10
  stage: test
  script:
    - ./gradlew --no-daemon test

release:
  image: google/cloud-sdk
  stage: release
  script:
    - env
    - gcloud config set project pro-tracker-some-id
    - gcloud auth activate-service-account --key-file=$CI_PROJECT_DIR/src/kubernetes/key.json
    - gcloud auth configure-docker
    - docker build -t "gcr.io/pro-tracker-some-id/joy-from-dance/joy-from-dance-website:$CI_COMMIT_TAG" -f "$CI_PROJECT_DIR/project_website/src/docker/Dockerfile" project_website
    - docker push "gcr.io/pro-tracker-some-id/joy-from-dance/joy-from-dance-delivery:$CI_COMMIT_TAG"
    - docker push "gcr.io/pro-tracker-some-id/joy-from-dance/joy-from-dance-jobs:$CI_COMMIT_TAG"
    - docker push "gcr.io/pro-tracker-some-id/joy-from-dance/joy-from-dance-rest:$CI_COMMIT_TAG"
    - docker push "gcr.io/pro-tracker-some-id/joy-from-dance/joy-from-dance-website:$CI_COMMIT_TAG"
    - gcloud container clusters get-credentials projectk8s --zone europe-west3-a --project pro-tracker-some-id
    - kubectl apply -f $CI_PROJECT_DIR/src/kubernetes/conf/
  only:
    - master
  when: manual
